--- !ruby/object:Jumpstart::Configuration
application_name: Tokani
business_name: Fluency, Inc.
domain: tokani.com
support_email: support@tokani.com
default_from_email: Tokani <support@tokani.com>
business_address: |-
  5921 Sutter Ave.
  Carmichael, California 95608
background_job_processor: sidekiq
email_provider: mailjet
personal_accounts: false
solargraph: false
register_with_account: true
apns: false
fcm: false
collect_billing_address: false
integrations:
- honeybadger
multitenancy:
- path
