puts "*************** creating Agencies / with primary contacts as owners and Details ***************"
load "db/seed_data/agencies.rb"
# load "db/seed_data/agency_details.rb"
# load "db/seed_data/agency_addresses.rb"
puts " "
puts "*************** creating Customers, Details, Categories ***************"
load "db/seed_data/customer_categories.rb"
load "db/seed_data/customers.rb"
puts " "
puts "*************** creating Agency Customers & Customer Agnecies ***************"
load "db/seed_data/agency_customers.rb"
puts " "
puts "*************** creating Languages ***************"
load "db/seed_data/languages.rb"
puts " "
puts "*************** creating Sites ***************"
load "db/seed_data/sites.rb"
puts " "
puts "*************** creating Interpreters ***************"
load "db/seed_data/interpreters.rb"
puts " "
puts "*************** creating Appointments ***************"
load "db/seed_data/appointments.rb"
puts " "

puts "*************** creating Super Admin ***************"
load "db/seed_data/super_admin.rb"
puts " "
